'use strict';
// This fixture was generated by the original v1-v3 Python codec, not this implementation.
const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');
const vdf = require('../src/main/vdf');
const steam = require('../src/main/steam');

const FIXTURE = path.join(__dirname, 'fixtures', 'shortcuts-2entries.vdf');

describe('vdf codec', () => {
  it('parses the Python-produced fixture', () => {
    const parsed = vdf.loadShortcuts(FIXTURE);
    assert.equal(parsed.length, 2);
    assert.equal(parsed[0].AppName, 'My Game');
    assert.equal(parsed[0].Exe, '"C:\\Games\\My Game\\game.exe"');
    assert.equal(parsed[0].tags['0'], 'SGDB Manager');
    assert.equal(parsed[1].AppName, 'Second');
    assert.ok(Number.isInteger(parsed[1].appid));
    assert.ok(parsed[1].appid < 0, 'appid is signed int32');
  });

  it('re-encodes to identical bytes', () => {
    const e1 = steam.buildEntry({ appName: 'My Game', exePath: 'C:\\Games\\My Game\\game.exe', startDir: 'C:\\Games\\My Game', tags: ['SGDB Manager'] });
    const e2 = steam.buildEntry({ appName: 'Second', exePath: 'D:\\G\\Second\\second.exe', startDir: 'D:\\G\\Second' });
    assert.deepEqual(vdf.dumpShortcuts([e1, e2]), fs.readFileSync(FIXTURE));
  });

  it('upsert keeps entries dense and stable', () => {
    const entries = [];
    const a = steam.buildEntry({ appName: 'A', exePath: 'C:\\A\\a.exe', startDir: 'C:\\A', tags: ['SGDB Manager'] });
    const r1 = steam.upsertEntry(entries, a);
    assert.equal(r1.index, 0);
    assert.equal(r1.updated, false);
    const r2 = steam.upsertEntry(entries, { ...a, LaunchOptions: '-x' });
    assert.equal(r2.index, 0);
    assert.equal(r2.updated, true);
    assert.equal(entries[0].LaunchOptions, '-x');
  });

  it('does not adopt or replace shortcuts made elsewhere', () => {
    const foreign = steam.buildEntry({ appName: 'Same name', exePath: 'C:\\Old\\game.exe', launchOptions: '-old' });
    const original = structuredClone(foreign);
    const entries = [foreign];
    const exact = steam.buildEntry({ appName: 'New name', exePath: 'C:\\Old\\game.exe', tags: ['SGDB Manager'] });
    assert.equal(steam.upsertEntry(entries, exact).existing, true);
    assert.deepEqual(entries, [original]);

    const sameName = steam.buildEntry({ appName: 'Same name', exePath: 'D:\\New\\game.exe', tags: ['SGDB Manager'] });
    assert.equal(steam.upsertEntry(entries, sameName).updated, false);
    assert.equal(entries.length, 2);
    assert.deepEqual(entries[0], original);
  });

  it('keeps custom fields and tags when updating a managed shortcut', () => {
    const old = steam.buildEntry({
      appName: 'Old', exePath: 'C:\\Game\\game.exe', tags: ['SGDB Manager', 'Favorite'],
    });
    old.CustomField = 'keep';
    const entries = [old];
    const next = steam.buildEntry({
      appName: 'New', exePath: 'C:\\Game\\game.exe', launchOptions: '-new', tags: ['SGDB Manager'],
    });
    steam.upsertEntry(entries, next);
    assert.equal(entries[0].CustomField, 'keep');
    assert.equal(entries[0].LaunchOptions, '-new');
    assert.deepEqual(Object.values(entries[0].tags), ['SGDB Manager', 'Favorite']);
  });

  it('does not update a managed shortcut when nothing changed', () => {
    const entry = steam.buildEntry({
      appName: 'Game', exePath: 'C:\\Game\\game.exe', tags: ['SGDB Manager'],
    });
    const entries = [entry];
    const result = steam.upsertEntry(entries, structuredClone(entry));
    assert.equal(result.updated, false);
    assert.equal(result.existing, true);
  });

  it('keeps managed shortcuts with the same name separate', () => {
    const first = steam.buildEntry({
      appName: 'Same name', exePath: 'C:\\First\\game.exe', tags: ['SGDB Manager'],
    });
    const second = steam.buildEntry({
      appName: 'Same name', exePath: 'D:\\Second\\game.exe', tags: ['SGDB Manager'],
    });
    const entries = [first];
    const result = steam.upsertEntry(entries, second);
    assert.equal(result.updated, false);
    assert.equal(entries.length, 2);
    assert.equal(entries[0].Exe, '"C:\\First\\game.exe"');
    assert.equal(entries[1].Exe, '"D:\\Second\\game.exe"');
  });

  it('updates a verified managed shortcut after its exe changes', () => {
    const first = steam.buildEntry({
      appName: 'Game', exePath: 'C:\\Old\\game.exe', tags: ['SGDB Manager'],
    });
    const next = steam.buildEntry({
      appName: 'Game', exePath: 'D:\\New\\game.exe', tags: ['SGDB Manager'],
    });
    const entries = [first];
    const result = steam.upsertEntry(entries, next, 0);
    assert.equal(result.updated, true);
    assert.equal(entries.length, 1);
    assert.equal(entries[0].Exe, '"D:\\New\\game.exe"');
  });

  it('does not move a verified shortcut onto another shortcut exe', () => {
    const first = steam.buildEntry({
      appName: 'First', exePath: 'C:\\First\\game.exe', tags: ['SGDB Manager'],
    });
    const second = steam.buildEntry({
      appName: 'Second', exePath: 'D:\\Second\\game.exe', tags: ['SGDB Manager'],
    });
    const entries = [first, second];
    const changed = steam.buildEntry({
      appName: 'First', exePath: 'D:\\Second\\game.exe', tags: ['SGDB Manager'],
    });
    const result = steam.upsertEntry(entries, changed, 0);
    assert.equal(result.conflict, true);
    assert.equal(entries[0].Exe, '"C:\\First\\game.exe"');
    assert.equal(entries[1].AppName, 'Second');
  });

  it('never overwrites a backup made in the same instant', () => {
    const td = fs.mkdtempSync(path.join(os.tmpdir(), 'backup-'));
    const sp = path.join(td, 'Steam');
    const uid = '1';
    const file = steam.shortcutsPath(sp, uid);
    try {
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, 'first');
      const first = steam.backupShortcuts(sp, uid);
      fs.writeFileSync(file, 'second');
      const second = steam.backupShortcuts(sp, uid);
      assert.notEqual(first, second);
      assert.equal(fs.readFileSync(first, 'utf8'), 'first');
      assert.equal(fs.readFileSync(second, 'utf8'), 'second');
    } finally {
      fs.rmSync(td, { recursive: true, force: true });
    }
  });

  it('does not write when an existing shortcut backup fails', () => {
    const td = fs.mkdtempSync(path.join(os.tmpdir(), 'backup-fail-'));
    const sp = path.join(td, 'Steam');
    const uid = '1';
    const file = steam.shortcutsPath(sp, uid);
    const copy = fs.copyFileSync;
    try {
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, 'original');
      fs.copyFileSync = () => { throw new Error('blocked'); };
      assert.throws(() => steam.saveEntries(sp, uid, []), /Cannot back up shortcuts\.vdf/);
      assert.equal(fs.readFileSync(file, 'utf8'), 'original');
    } finally {
      fs.copyFileSync = copy;
      fs.rmSync(td, { recursive: true, force: true });
    }
  });

  it('round-trips through a real file', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'vdf-'));
    const file = path.join(dir, 'shortcuts.vdf');
    try {
      const e = steam.buildEntry({ appName: 'X', exePath: 'C:\\X\\x.exe', startDir: 'C:\\X' });
      vdf.saveShortcuts(file, [e]);
      const back = vdf.loadShortcuts(file);
      assert.equal(back.length, 1);
      assert.equal(back[0].AppName, 'X');
      assert.equal(fs.readdirSync(dir).filter((f) => f.endsWith('.tmp')).length, 0);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });
});
